import { createFileRoute, Link } from "@tanstack/react-router";
import * as Accordion from "@radix-ui/react-accordion";
import { ArrowRight, Check, ChevronDown, MessageCircle, Radio, ShieldCheck, Star } from "lucide-react";
import { Button } from "@/components/ui/button";
import { LeadForm } from "@/components/keymaster/LeadForm";
import { CTASection, SectionTitle, WhatsAppFloat } from "@/components/keymaster/Shared";
import { company, whatsappUrl } from "@/config/company";
import { faq, services, solutions } from "@/data/content";
import central from "@/assets/central-monitoramento.png.asset.json";
import camera from "@/assets/camera-seguranca.png.asset.json";
import team from "@/assets/equipe-viatura.png.asset.json";
import mobile from "@/assets/acesso-celular.png.asset.json";

const imgs={camera:camera.url,central:central.url,team:team.url,mobile:mobile.url};
const steps=["Projeto sob medida","Instalação profissional","Monitoramento 24h","Verificação e ação","Relatórios"];
const schema={"@context":"https://schema.org","@graph":[{"@type":["LocalBusiness","SecurityService"],name:company.name,foundingDate:"1991",telephone:"+55 11 2196-2200",email:company.email,address:{"@type":"PostalAddress",streetAddress:"Rua Calandra, 51",addressLocality:"São Paulo",addressRegion:"SP",postalCode:"02275-000",addressCountry:"BR"},openingHours:"Mo-Su 00:00-23:59"},{"@type":"FAQPage",mainEntity:faq.map(([q,a])=>({"@type":"Question",name:q,acceptedAnswer:{"@type":"Answer",text:a}}))}]};
export const Route=createFileRoute("/")({head:()=>({meta:[{title:"Key Master | Monitoramento 24h, Alarmes e Câmeras em São Paulo desde 1991"},{name:"description",content:"Monitoramento 24 horas, alarmes e câmeras em São Paulo com central e viaturas próprias. Peça um orçamento gratuito à Key Master."},{property:"og:title",content:"Key Master | Segurança e Monitoramento 24h"},{property:"og:description",content:"Há mais de 35 anos protegendo casas, empresas e condomínios com central própria em São Paulo."},{property:"og:type",content:"website"},{property:"og:url",content:"/"},{name:"twitter:card",content:"summary_large_image"}],links:[{rel:"canonical",href:"/"}],scripts:[{type:"application/ld+json",children:JSON.stringify(schema)}]}),component:Home});

function Home(){return <main>
<section className="dot-grid relative min-h-[760px] overflow-hidden bg-primary-dark pb-20 pt-40 text-hero-foreground md:pt-52"><div className="absolute inset-0 opacity-15"><img src={camera.url} alt="Câmera de segurança Key Master protegendo uma residência" className="h-full w-full object-cover" /></div><div className="absolute inset-0 bg-primary-dark/75"/><div className="relative mx-auto grid max-w-7xl items-center gap-12 px-4 lg:grid-cols-[1.15fr_.85fr] lg:px-6"><div className="reveal"><span className="inline-flex rounded-full border border-hero-foreground/25 px-4 py-2 text-sm font-semibold">Desde 1991 • Central própria 24h</span><h1 className="mt-6 max-w-4xl text-[clamp(2rem,5vw,3.5rem)] font-bold leading-[1.1]">Segurança 24 horas com quem protege São Paulo há mais de 35 anos</h1><p className="mt-6 max-w-2xl text-lg leading-relaxed text-silver">Alarmes monitorados, câmeras inteligentes e viaturas de apoio próprias. Tecnologia de ponta e atendimento humano para sua casa, empresa ou condomínio.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Button asChild size="lg"><a href="#orcamento">Quero meu orçamento grátis<ArrowRight/></a></Button><Button asChild variant="light" size="lg"><a href={whatsappUrl()} target="_blank" rel="noreferrer"><MessageCircle/>Falar no WhatsApp</a></Button></div><div className="mt-8 flex flex-wrap gap-5 text-sm">{["Central própria 24h","Viaturas de apoio","+2.000 clientes"].map(x=><span key={x} className="flex items-center gap-2"><Check className="size-4 text-accent"/>{x}</span>)}</div></div><div className="reveal rounded-2xl border border-hero-foreground/20 bg-hero-foreground/10 p-6 shadow-soft backdrop-blur-xl"><div className="flex items-center justify-between"><span className="font-display font-bold">Key Master Central</span><span className="flex items-center gap-2 text-sm"><i className="pulse-status size-2 rounded-full bg-success"/>Online</span></div><div className="mt-6 rounded-xl bg-primary-dark/75 p-5"><p className="text-sm text-silver">Status do imóvel</p><p className="mt-2 flex items-center gap-2 text-xl font-bold"><ShieldCheck className="text-success"/>Sistema armado</p></div><div className="mt-3 grid grid-cols-2 gap-3"><div className="rounded-xl border border-hero-foreground/10 p-4"><p className="text-xs text-silver">Última verificação</p><strong className="mt-1 block">Agora</strong></div><div className="rounded-xl border border-hero-foreground/10 p-4"><p className="text-xs text-silver">Conexão</p><strong className="mt-1 block">Protegida</strong></div></div></div></div></section>
<section className="py-10"><div className="mx-auto grid max-w-7xl grid-cols-2 gap-6 px-4 text-center md:grid-cols-4 lg:px-6">{[["1991","fundada há mais de 35 anos"],["+2.000","clientes monitorados"],["24h","central própria, todos os dias"],["940m²","sede própria no Tucuruvi"]].map(([n,t])=><div key={n}><strong className="font-display text-3xl text-accent md:text-4xl">{n}</strong><p className="mt-2 text-sm text-muted-foreground">{t}</p></div>)}</div></section>
<section className="bg-primary-soft py-20"><div className="mx-auto max-w-7xl px-4 lg:px-6"><SectionTitle eyebrow="Soluções" title="Qual espaço você quer proteger?"/><div className="flex snap-x gap-5 overflow-x-auto pb-5 md:grid md:grid-cols-2 lg:grid-cols-4 md:overflow-visible">{solutions.map(x=><article key={x.slug} className="group min-w-[82vw] snap-center overflow-hidden rounded-2xl border border-border bg-background shadow-soft transition hover:-translate-y-1 hover:border-accent sm:min-w-[360px] md:min-w-0"><img src={imgs[x.image as keyof typeof imgs]} alt={`${x.title}: solução de segurança eletrônica Key Master`} loading="lazy" width="520" height="340" className="aspect-[4/3] w-full object-cover"/><div className="p-5"><x.icon className="text-accent"/><h3 className="mt-4 text-xl font-bold text-primary">{x.title}</h3><p className="mt-2 text-sm text-muted-foreground">{x.short}</p><Link to={`/solucoes/${x.slug}`} className="mt-5 inline-flex min-h-12 items-center gap-2 font-semibold text-primary">Ver solução <ArrowRight className="size-4"/></Link></div></article>)}</div></div></section>
<section className="py-20"><div className="mx-auto max-w-7xl px-4 lg:px-6"><SectionTitle eyebrow="Proteção completa" title="Tecnologia e resposta em um só lugar" copy="Projetamos, instalamos, monitoramos e mantemos sua segurança com equipe própria."/><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{services.map(s=><article key={s.slug} className="rounded-2xl border border-border p-6 transition hover:-translate-y-1 hover:border-accent hover:shadow-soft"><span className="flex size-12 items-center justify-center rounded-full bg-primary-soft"><s.icon className="text-primary"/></span><h3 className="mt-5 text-lg font-bold text-primary">{s.title}</h3><p className="mt-3 text-sm leading-relaxed text-muted-foreground">{s.description}</p><Link to={`/servicos/${s.slug}`} className="mt-4 inline-flex min-h-12 items-center gap-2 font-semibold text-primary">Conhecer serviço<ArrowRight className="size-4"/></Link></article>)}</div><div className="mt-10 text-center"><Button asChild size="lg"><Link to="/contato">Solicitar visita técnica gratuita</Link></Button></div></div></section>
<section className="bg-primary-soft py-20"><div className="mx-auto max-w-7xl px-4 lg:px-6"><SectionTitle eyebrow="Como funciona" title="Do disparo à solução: veja como protegemos você"/><ol className="grid gap-8 lg:grid-cols-5">{steps.map((s,i)=><li key={s} className="relative"><span className="font-display text-5xl font-bold text-accent">0{i+1}</span><h3 className="mt-3 font-bold text-primary">{s}</h3><p className="mt-2 text-sm text-muted-foreground">{["Avaliamos seu imóvel e criamos o projeto ideal.","Equipe própria instala e configura os equipamentos.","A central recebe sinais por GPRS, IP ou linha.","Verificamos por imagem e enviamos apoio quando necessário.","Você acompanha eventos e solicita históricos."][i]}</p></li>)}</ol></div></section>
<section className="dot-grid bg-primary-dark py-20 text-hero-foreground"><div className="mx-auto grid max-w-7xl items-center gap-12 px-4 lg:grid-cols-2 lg:px-6"><img src={central.url} alt="Operadores da central própria de monitoramento Key Master" loading="lazy" width="960" height="640" className="w-full rounded-2xl object-cover shadow-soft"/><div><p className="text-xs font-bold uppercase text-accent">Central própria 24h</p><h2 className="mt-3 text-3xl font-bold md:text-4xl">Nossa central não dorme. E ela é nossa.</h2><p className="mt-5 leading-relaxed text-silver">A Key Master opera sua própria central na sede em São Paulo, com software desenvolvido internamente, sistemas duplicados e operadores treinados em três turnos.</p><ul className="mt-7 grid gap-4 sm:grid-cols-2">{["Central própria 365 dias","Software próprio","Redundância total","Viaturas exclusivas","Sinais de todo o Brasil","Compatível com várias marcas"].map(x=><li key={x} className="flex gap-2 text-sm"><Check className="size-5 text-accent"/>{x}</li>)}</ul><Button asChild className="mt-8"><Link to="/sobre">Conheça a Key Master</Link></Button></div></div></section>
<section className="py-20"><div className="mx-auto max-w-7xl px-4 lg:px-6"><SectionTitle title="Segurança de empresa grande, atendimento de quem conhece você"/><div className="grid gap-8 md:grid-cols-3">{[["Estrutura própria","Central, sede, tecnologia e viaturas sob nossa gestão."],["Atendimento próximo","Gente de verdade, disponível quando você precisa."],["Projeto personalizado","Proteção desenhada para o risco e a rotina do seu imóvel."]].map(([a,b])=><div key={a} className="border-t-2 border-accent pt-5"><h3 className="text-xl font-bold text-primary">{a}</h3><p className="mt-3 text-muted-foreground">{b}</p></div>)}</div></div></section>
<section className="bg-primary-soft py-20"><div className="mx-auto max-w-7xl px-4 lg:px-6"><SectionTitle eyebrow="Confiança" title="Quem escolhe a Key Master fica tranquilo"/><div className="grid gap-5 md:grid-cols-3">{["Síndica — Condomínio na Zona Norte","Gestor — Comércio em São Paulo","Moradora — Residência no Tucuruvi"].map((x,i)=><blockquote key={x} className="rounded-2xl bg-background p-6 shadow-soft"><div className="flex text-accent">{[1,2,3,4,5].map(n=><Star key={n} className="size-4 fill-current"/>)}</div><p className="mt-4 leading-relaxed">[DEPOIMENTO EXEMPLO] “Atendimento rápido, equipe cuidadosa e a tranquilidade de saber que há uma central acompanhando tudo.”</p><footer className="mt-5 text-sm font-semibold text-primary">{x}</footer></blockquote>)}</div><div className="mt-8 grid gap-3 text-center text-xs text-muted-foreground md:grid-cols-3"><div className="rounded-lg border border-dashed border-silver p-5">[PLACEHOLDER] Avaliações no Google</div><div className="rounded-lg border border-dashed border-silver p-5">[PLACEHOLDER] Marcas de equipamentos</div><div className="rounded-lg border border-dashed border-silver p-5">[CONFIRMAR COM A CLIENTE] Autorização PF</div></div></div></section>
<section id="orcamento" className="bg-primary-soft py-20"><div className="mx-auto max-w-5xl px-4"><SectionTitle eyebrow="Orçamento gratuito" title="Receba seu orçamento em menos de 1 minuto" copy="Conte o que você precisa. Nossa equipe entra em contato para orientar o próximo passo."/><LeadForm/></div></section>
<section className="py-20"><div className="mx-auto max-w-4xl px-4"><SectionTitle eyebrow="Dúvidas frequentes" title="Informação clara para você decidir"/><Accordion.Root type="single" collapsible className="divide-y divide-border border-y border-border">{faq.map(([q,a],i)=><Accordion.Item value={`f${i}`} key={q}><Accordion.Header><Accordion.Trigger className="group flex min-h-16 w-full items-center justify-between py-4 text-left font-semibold text-primary">{q}<ChevronDown className="shrink-0 transition-transform group-data-[state=open]:rotate-180"/></Accordion.Trigger></Accordion.Header><Accordion.Content className="overflow-hidden pb-5 text-muted-foreground data-[state=closed]:animate-accordion-up data-[state=open]:animate-accordion-down">{a}</Accordion.Content></Accordion.Item>)}</Accordion.Root></div></section>
<CTASection/><WhatsAppFloat/></main>}
