import { Link, useRouterState } from "@tanstack/react-router";
import { ChevronDown, Facebook, Instagram, Menu, MessageCircle, Phone, ShieldCheck, X } from "lucide-react";
import { useEffect, useState, type ReactNode } from "react";
import { Button } from "@/components/ui/button";
import { company, trackEvent, whatsappUrl } from "@/config/company";
import logo from "@/assets/key-master-logo.png.asset.json";
import { services, solutions } from "@/data/content";

function Dropdown({ label, children }: { label: string; children: ReactNode }) {
  return <div className="group relative"><span className="flex min-h-12 cursor-default items-center gap-1 text-sm font-medium text-foreground">{label}<ChevronDown className="size-4" /></span><div className="invisible absolute left-0 top-full z-50 w-72 translate-y-2 rounded-lg border border-border bg-background p-2 opacity-0 shadow-soft transition-all group-hover:visible group-hover:translate-y-0 group-hover:opacity-100 group-focus-within:visible group-focus-within:opacity-100">{children}</div></div>;
}

export function SiteChrome({ children }: { children: ReactNode }) {
  const [open, setOpen] = useState(false);
  const [scrolled, setScrolled] = useState(false);
  const [fontScale, setFontScale] = useState(100);
  const path = useRouterState({ select: (s) => s.location.pathname });
  useEffect(() => { setOpen(false); }, [path]);
  useEffect(() => { const fn = () => setScrolled(window.scrollY > 30); fn(); window.addEventListener("scroll", fn); return () => window.removeEventListener("scroll", fn); }, []);
  useEffect(() => { document.documentElement.style.fontSize = `${fontScale}%`; }, [fontScale]);
  useEffect(() => { if (!open) return; const fn = (e: KeyboardEvent) => e.key === "Escape" && setOpen(false); window.addEventListener("keydown", fn); return () => window.removeEventListener("keydown", fn); }, [open]);
  return <>
    <header className="fixed inset-x-0 top-0 z-50">
      <div className={`hidden bg-primary-dark text-hero-foreground transition-all md:block ${scrolled ? "h-0 overflow-hidden" : "h-9"}`}><div className="mx-auto flex h-9 max-w-7xl items-center justify-between px-6 text-xs"><span className="flex items-center gap-2"><i className="pulse-status size-2 rounded-full bg-success" />Central de Monitoramento online 24h — Já é cliente? <a href={company.centralPhoneHref} className="font-bold">Ligue {company.centralPhone}</a></span><div className="flex items-center gap-3"><span className="text-silver">Tamanho do texto</span><button aria-label="Diminuir tamanho do texto" onClick={() => setFontScale(90)} className="min-h-8 min-w-8">A−</button><button aria-label="Aumentar tamanho do texto" onClick={() => setFontScale(110)} className="min-h-8 min-w-8">A+</button><Instagram className="size-4" aria-label="Instagram [PLACEHOLDER]" /><Facebook className="size-4" aria-label="Facebook [PLACEHOLDER]" /></div></div></div>
      <div className={`border-b transition-all ${scrolled || path !== "/" ? "border-border bg-background/95 shadow-sm backdrop-blur" : "border-hero-foreground/10 bg-primary-dark/80 backdrop-blur"}`}><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-4 lg:px-6"><Link to="/" aria-label="Key Master — início" className="rounded-lg bg-background/95 px-2 py-1"><img src={logo.url} alt="Key Master Monitoramento 24 Horas" className="h-12 w-auto max-w-44 object-contain" /></Link><nav aria-label="Navegação principal" className={`hidden items-center gap-5 lg:flex ${!scrolled && path === "/" ? "[&_span]:text-hero-foreground [&_a]:text-hero-foreground" : ""}`}><Link to="/" className="text-sm font-medium">Início</Link><Dropdown label="Soluções">{solutions.map((x) => <Link key={x.slug} to="/solucoes/$slug" params={{ slug: x.slug }} className="block rounded-md px-3 py-3 text-sm hover:bg-primary-soft">{x.title}</Link>)}</Dropdown><Dropdown label="Serviços">{services.map((x) => <Link key={x.slug} to="/servicos/$slug" params={{ slug: x.slug }} className="block rounded-md px-3 py-3 text-sm hover:bg-primary-soft">{x.title}</Link>)}</Dropdown><Link to="/como-funciona" className="text-sm font-medium">Como Funciona</Link><Link to="/sobre" className="text-sm font-medium">Sobre</Link><Link to="/contato" className="text-sm font-medium">Contato</Link></nav><div className="hidden items-center gap-3 xl:flex"><a href={company.centralPhoneHref} onClick={() => trackEvent("phone_click", { placement: "header" })} className={`flex items-center gap-2 text-sm font-semibold ${!scrolled && path === "/" ? "text-hero-foreground" : "text-primary"}`}><Phone className="size-4" />Central 24h<br />{company.centralPhone}</a><Button asChild><Link to="/contato">Orçamento grátis</Link></Button></div><Button variant="ghost" size="icon" className={`lg:hidden ${!scrolled && path === "/" ? "text-hero-foreground" : "text-primary"}`} aria-label="Abrir menu" onClick={() => setOpen(true)}><Menu /></Button></div></div>
    </header>
    {open && <div className="fixed inset-0 z-[60] bg-primary-dark/60" onMouseDown={() => setOpen(false)}><aside role="dialog" aria-modal="true" aria-label="Menu" className="ml-auto flex h-dvh w-[88%] max-w-sm flex-col overflow-y-auto bg-background p-5" onMouseDown={(e) => e.stopPropagation()}><div className="flex items-center justify-between"><img src={logo.url} alt="" className="h-12 w-auto" /><Button variant="ghost" size="icon" aria-label="Fechar menu" onClick={() => setOpen(false)}><X /></Button></div><nav className="mt-7 flex flex-col gap-1"><Link to="/" className="flex min-h-12 items-center border-b border-border font-semibold">Início</Link><Link to="/como-funciona" className="flex min-h-12 items-center border-b border-border font-semibold">Como Funciona</Link><Link to="/sobre" className="flex min-h-12 items-center border-b border-border font-semibold">Sobre</Link><Link to="/contato" className="flex min-h-12 items-center border-b border-border font-semibold">Contato</Link><p className="mt-5 text-xs font-bold uppercase text-muted-foreground">Soluções</p>{solutions.map(x=><Link key={x.slug} to="/solucoes/$slug" params={{ slug: x.slug }} className="flex min-h-12 items-center text-sm">{x.title}</Link>)}<p className="mt-5 text-xs font-bold uppercase text-muted-foreground">Serviços</p>{services.map(x=><Link key={x.slug} to="/servicos/$slug" params={{ slug: x.slug }} className="flex min-h-12 items-center text-sm">{x.title}</Link>)}</nav><div className="mt-auto grid gap-2 pt-6"><Button asChild variant="outline"><a href={company.centralPhoneHref}><Phone />Ligar</a></Button><Button asChild variant="whatsapp"><a href={whatsappUrl()}><MessageCircle />WhatsApp</a></Button><Button asChild><Link to="/contato">Orçamento</Link></Button></div></aside></div>}
    {children}
    <MobileActions />
    <CookieBanner />
  </>;
}

function MobileActions() { return <div className="fixed inset-x-0 bottom-0 z-40 grid grid-cols-3 border-t border-border bg-background p-2 shadow-soft md:hidden"><Button asChild variant="ghost"><a href={company.centralPhoneHref}><Phone />Ligar</a></Button><Button asChild variant="whatsapp"><a href={whatsappUrl()}><MessageCircle />WhatsApp</a></Button><Button asChild><Link to="/contato">Orçamento</Link></Button></div>; }
function CookieBanner() { const [show,setShow]=useState(false); useEffect(()=>setShow(localStorage.getItem("km-cookie-choice")===null),[]); if(!show)return null; const choose=(v:string)=>{localStorage.setItem("km-cookie-choice",v);setShow(false)}; return <div className="fixed bottom-24 left-4 right-4 z-50 mx-auto max-w-2xl rounded-lg border border-border bg-background p-4 shadow-soft md:bottom-6"><div className="flex flex-col items-start gap-3 sm:flex-row sm:items-center"><ShieldCheck className="shrink-0 text-primary" /><p className="text-sm text-muted-foreground">Usamos cookies essenciais e, com sua permissão, dados de navegação. Consulte a <Link to="/politica-de-privacidade" className="font-semibold text-primary underline">Política de Privacidade</Link>.</p><div className="flex gap-2"><Button variant="outline" onClick={()=>choose("rejected")}>Recusar</Button><Button onClick={()=>choose("accepted")}>Aceitar</Button></div></div></div>; }
